// This file is auto-generated by scripts/sync-prompts.js.
// Do not edit manually.

export const SYSTEM_PROMPTS = [
  {
    id: "weekly-planning-coach",
    title: "🧠 Weekly Planning Coach",
    prompt:
      "Act as a weekly productivity coach. Reflect on the following input from my past week: {past_week_summary}. Based on that, generate a plan for the coming week, including top 3 goals, habits to track, and key lessons.",
    category: "Awesome Prompts",
    tags: ["planning"],
  },
  {
    id: "time-blocking-scheduler",
    title: "🧠 Time Blocking Scheduler",
    prompt:
      "You are a time-blocking expert. I’ll give you my tasks for today: {task_list}. Arrange them into a realistic hourly schedule from 9AM–6PM with focus blocks, breaks, and buffer time.",
    category: "Awesome Prompts",
    tags: ["time_management"],
  },
  {
    id: "learn-anything-10x-faster",
    title: "🧠 Learn Anything 10x Faster",
    prompt:
      "I want to learn {your_topic}. Create a 4-week learning roadmap using fast learning techniques like active recall, Feynman technique, spaced repetition, and real-world practice.",
    category: "Awesome Prompts",
    tags: ["learning"],
  },
  {
    id: "daily-standup-reflector",
    title: "🧠 Daily Standup Reflector",
    prompt:
      "Ask me: 1) What did I do yesterday? 2) What’s the plan today? 3) What’s blocking me? Then respond with encouragement and a focus reminder.",
    category: "Awesome Prompts",
    tags: ["standup"],
  },
  {
    id: "eisenhower-prioritizer",
    title: "🧠 Eisenhower Prioritizer",
    prompt:
      "Here’s my current list of tasks: {task_list}. Categorize them into the Eisenhower matrix and suggest what I should Do, Schedule, Delegate, or Delete.",
    category: "Awesome Prompts",
    tags: ["prioritization"],
  },
  {
    id: "digital-brain-architect",
    title: "🧠 Digital Brain Architect",
    prompt:
      "I want to build a second brain for {your_use_case} using Notion. Help me create a dashboard structure, templates, and tagging system.",
    category: "Awesome Prompts",
    tags: ["pkm"],
  },
  {
    id: "decision-clarity-sheet",
    title: "🧠 Decision Clarity Sheet",
    prompt:
      "Help me decide: {your_decision}. Ask me clarifying questions, list pros/cons, and help simulate possible outcomes.",
    category: "Awesome Prompts",
    tags: ["decisions"],
  },
  {
    id: "email-rewrite-assistant",
    title: "🧠 Email Rewrite Assistant",
    prompt:
      "Here’s a messy email draft: {your_draft}. Rewrite it to be clear, concise, and polite, but still assertive.",
    category: "Awesome Prompts",
    tags: ["communication"],
  },
  {
    id: "productivity-systems-generator",
    title: "🧠 Productivity Systems Generator",
    prompt:
      "I’m a {role/personality} who struggles with {problem}. Suggest a personal productivity system that suits me and helps solve this.",
    category: "Awesome Prompts",
    tags: ["systems"],
  },
  {
    id: "motivation-reboot",
    title: "🧠 Motivation Reboot",
    prompt:
      "I’m feeling unmotivated about {your_project}. Help me reconnect with the deeper purpose, reframe the struggle, and suggest small momentum actions.",
    category: "Awesome Prompts",
    tags: ["motivation"],
  },
  {
    id: "parkinson-s-law-time-cruncher",
    title: "🧠 Parkinson’s Law Time Cruncher",
    prompt:
      "I have to do {task}. Help me plan to complete it in half the usual time using constraints, tight focus, and urgency.",
    category: "Awesome Prompts",
    tags: ["urgency"],
  },
  {
    id: "atomic-habits-builder",
    title: "🧠 Atomic Habits Builder",
    prompt:
      "Help me build a habit for {your_goal}. Use Atomic Habits principles to design cues, routines, rewards, and identity reinforcement.",
    category: "Awesome Prompts",
    tags: ["habits"],
  },
  {
    id: "anti-burnout-planner",
    title: "🧠 Anti-Burnout Planner",
    prompt:
      "I'm feeling overwhelmed. Help me redesign my weekly schedule for energy balance, rest, deep work, and recovery activities.",
    category: "Awesome Prompts",
    tags: ["burnout"],
  },
  {
    id: "personal-okrs-generator",
    title: "🧠 Personal OKRs Generator",
    prompt:
      "Help me define 3 personal OKRs for the next 90 days around {focus_area}. Include measurable key results.",
    category: "Awesome Prompts",
    tags: ["goal_setting"],
  },
  {
    id: "ai-accountability-partner",
    title: "🧠 AI Accountability Partner",
    prompt:
      "Act as my accountability partner. Check in daily to ask about these goals: {goals}. If I skip, remind me of my “why.”",
    category: "Awesome Prompts",
    tags: ["accountability"],
  },
  {
    id: "distraction-audit",
    title: "🧠 Distraction Audit",
    prompt:
      "Guide me through a distraction audit. Ask about where I lose time, attention traps, and help create digital barriers.",
    category: "Awesome Prompts",
    tags: ["distractions"],
  },
  {
    id: "book-summary-synthesizer",
    title: "🧠 Book Summary Synthesizer",
    prompt:
      "Here's my book highlights: {paste_highlights}. Summarize key takeaways, core ideas, and 3 things I can apply.",
    category: "Awesome Prompts",
    tags: ["reading"],
  },
  {
    id: "second-brain-cleanup",
    title: "🧠 Second Brain Cleanup",
    prompt:
      "Here’s a list of folders and files from my system: {paste_list}. Help me categorize, archive, delete, and create a better structure.",
    category: "Awesome Prompts",
    tags: ["digital_organization"],
  },
  {
    id: "deep-work-mode-enabler",
    title: "🧠 Deep Work Mode Enabler",
    prompt:
      "I want to enter Deep Work mode for {your_task}. Guide me through a 3-min ritual to set intention, remove distraction, and get started.",
    category: "Awesome Prompts",
    tags: ["deep_work"],
  },
  {
    id: "digital-detox-planner",
    title: "🧠 Digital Detox Planner",
    prompt:
      "Help me plan a 24-hour digital detox. Suggest activities, routines, rules, and how to handle withdrawal urges.",
    category: "Awesome Prompts",
    tags: ["digital_detox"],
  },
  {
    id: "personal-manifesto-writer",
    title: "🧠 Personal Manifesto Writer",
    prompt:
      "Guide me through writing a 1-page personal manifesto about my values, identity, non-negotiables, and vision.",
    category: "Awesome Prompts",
    tags: ["values"],
  },
  {
    id: "5-minute-journal-generator",
    title: "🧠 5-Minute Journal Generator",
    prompt:
      "Generate a 5-minute journal prompt set for either morning or evening. Include gratitude, intention, and reflection sections.",
    category: "Awesome Prompts",
    tags: ["journaling"],
  },
  {
    id: "dopamine-detox-starter-pack",
    title: "🧠 Dopamine Detox Starter Pack",
    prompt:
      "Create a dopamine detox routine I can do for one day. Focus on removing high-dopamine habits and replacing them with low-stimulation activities.",
    category: "Awesome Prompts",
    tags: ["dopamine"],
  },
  {
    id: "just-one-thing-prioritizer",
    title: "🧠 Just-One-Thing Prioritizer",
    prompt:
      "Based on my to-do list: {paste_tasks}, help me pick *just one* that makes today successful.",
    category: "Awesome Prompts",
    tags: ["essentialism"],
  },
  {
    id: "sleep-optimization-plan",
    title: "🧠 Sleep Optimization Plan",
    prompt:
      "I want to optimize my sleep. Based on my current bed time {bed_time}, wake time {wake_time}, and lifestyle factors {lifestyle_notes}, create a 4-week sleep improvement plan with tips, rituals, and metrics to track.",
    category: "Awesome Prompts",
    tags: ["sleep"],
  },
  {
    id: "pomodoro-session-architect",
    title: "🧠 Pomodoro Session Architect",
    prompt:
      "I need to use Pomodoro for {task_list}. Suggest a sequence of 25/5 and 50/10 intervals, including when to take micro-breaks and longer breaks.",
    category: "Awesome Prompts",
    tags: ["pomodoro"],
  },
  {
    id: "weekly-retrospective-analyzer",
    title: "🧠 Weekly Retrospective Analyzer",
    prompt:
      "Here’s my week’s journal: {journal_entries}. Summarize wins, pain points, and suggest three improvements for next week.",
    category: "Awesome Prompts",
    tags: ["retrospective"],
  },
  {
    id: "smart-goals-creator",
    title: "🧠 SMART Goals Creator",
    prompt:
      "Help me turn my goal “{raw_goal}” into a SMART goal with clear metrics and deadlines.",
    category: "Awesome Prompts",
    tags: ["goal_setting"],
  },
  {
    id: "vision-board-designer",
    title: "🧠 Vision Board Designer",
    prompt:
      "Create a vision board for my next 5 years focused on {life_domain}, using vivid descriptions, quotes, and milestone markers.",
    category: "Awesome Prompts",
    tags: ["vision"],
  },
  {
    id: "energy-peak-planner",
    title: "🧠 Energy Peak Planner",
    prompt:
      "My energy peaks at {peak_times} and dips at {low_times}. Suggest a daily task schedule matching difficulty to energy levels.",
    category: "Awesome Prompts",
    tags: ["energy_management"],
  },
  {
    id: "procrastination-debrief",
    title: "🧠 Procrastination Debrief",
    prompt:
      "I keep avoiding {task}. Ask me questions to uncover root causes, then propose three tactics to overcome my procrastination.",
    category: "Awesome Prompts",
    tags: ["procrastination"],
  },
  {
    id: "meeting-efficiency-consultant",
    title: "🧠 Meeting Efficiency Consultant",
    prompt:
      "Here’s my meeting purpose and topics: {agenda_items}. Optimize it for 30 minutes, include time allocations and decision points.",
    category: "Awesome Prompts",
    tags: ["meetings"],
  },
  {
    id: "creative-brainstorm-facilitator",
    title: "🧠 Creative Brainstorm Facilitator",
    prompt:
      "I need ideas for {challenge}. Lead me through SCAMPER or mind-mapping prompts to generate 20 novel ideas.",
    category: "Awesome Prompts",
    tags: ["brainstorming"],
  },
  {
    id: "communication-tone-adjuster",
    title: "🧠 Communication Tone Adjuster",
    prompt:
      "Rewrite this message in a {desired_tone} tone: {original_text}. Keep all key points but adapt voice and length.",
    category: "Awesome Prompts",
    tags: ["writing"],
  },
  {
    id: "focus-prompt-for-deep-reading",
    title: "🧠 Focus Prompt for Deep Reading",
    prompt:
      "I’m reading {text_excerpt}. Ask me five analytical questions, then summarize the core arguments and personal takeaways.",
    category: "Awesome Prompts",
    tags: ["reading"],
  },
  {
    id: "mind-map-generator",
    title: "🧠 Mind Map Generator",
    prompt:
      "Create a mind map for {central_concept}. List main branches, sub-branches, and possible connections in markdown.",
    category: "Awesome Prompts",
    tags: ["mindmap"],
  },
  {
    id: "serene-morning-routine-designer",
    title: "🧠 Serene Morning Routine Designer",
    prompt:
      "Design a 60-minute morning routine for me, balancing mental, physical, and planning activities.",
    category: "Awesome Prompts",
    tags: ["morning_routine"],
  },
  {
    id: "evening-unwind-guide",
    title: "🧠 Evening Unwind Guide",
    prompt:
      "I’m usually wired at night. Suggest a 45-minute evening routine to relax mentally and physically.",
    category: "Awesome Prompts",
    tags: ["evening_routine"],
  },
  {
    id: "mindfulness-micro-practices",
    title: "🧠 Mindfulness Micro-Practices",
    prompt:
      "Give me five 2-minute mindfulness practices I can do during work breaks.",
    category: "Awesome Prompts",
    tags: ["mindfulness"],
  },
  {
    id: "stress-management-playbook",
    title: "🧠 Stress Management Playbook",
    prompt:
      "I’m stressed about {stressor}. Outline a 5-step playbook including immediate relief and long-term strategies.",
    category: "Awesome Prompts",
    tags: ["stress"],
  },
  {
    id: "cognitive-bias-checker",
    title: "🧠 Cognitive Bias Checker",
    prompt:
      "Here’s my decision rationale: {rationale_text}. Highlight any biases (confirmation, anchoring, etc.) and propose adjustments.",
    category: "Awesome Prompts",
    tags: ["bias"],
  },
  {
    id: "negotiation-prep-pro",
    title: "🧠 Negotiation Prep Pro",
    prompt:
      "I have to negotiate {scenario}. Help me outline my BATNA, their interests, opening offer, and 3 strategic concessions.",
    category: "Awesome Prompts",
    tags: ["negotiation"],
  },
  {
    id: "networking-outreach-planner",
    title: "🧠 Networking Outreach Planner",
    prompt:
      "I want to connect with {contact_role} at {company}. Write three versioned outreach messages: friendly intro, value-first, and mutual-interest.",
    category: "Awesome Prompts",
    tags: ["networking"],
  },
  {
    id: "learning-flashcards-creator",
    title: "🧠 Learning Flashcards Creator",
    prompt:
      "Here’s a text on {topic}: {paste_text}. Generate 10 cloze flashcards and 10 Q/A flashcards.",
    category: "Awesome Prompts",
    tags: ["learning"],
  },
  {
    id: "content-idea-generator",
    title: "🧠 Content Idea Generator",
    prompt:
      "Generate 30 content ideas for {platform} about {your_topic}, including titles and brief outlines.",
    category: "Awesome Prompts",
    tags: ["content_marketing"],
  },
  {
    id: "presentation-outline-builder",
    title: "🧠 Presentation Outline Builder",
    prompt:
      "I need a 10-slide deck on {topic} for {audience}. Provide slide titles and key bullet points.",
    category: "Awesome Prompts",
    tags: ["presentations"],
  },
  {
    id: "grant-proposal-drafting-assistant",
    title: "🧠 Grant Proposal Drafting Assistant",
    prompt:
      "Help me draft the “Project Description” section for a grant on {project_theme}. Include objectives, methods, and impact.",
    category: "Awesome Prompts",
    tags: ["grant_writing"],
  },
  {
    id: "resume-bullet-point-optimizer",
    title: "🧠 Resume Bullet Point Optimizer",
    prompt:
      "Here’s my resume line: {raw_line}. Rewrite it with the STAR method to emphasize impact and metrics.",
    category: "Awesome Prompts",
    tags: ["career"],
  },
  {
    id: "interview-prep-coach",
    title: "🧠 Interview Prep Coach",
    prompt:
      "I’m interviewing for {role}. Provide 5 behavioral questions and model answers using Situation–Task–Action–Result.",
    category: "Awesome Prompts",
    tags: ["interview"],
  },
  {
    id: "financial-budget-maker",
    title: "🧠 Financial Budget Maker",
    prompt:
      "My monthly net income is {income}. List all expense categories, allocate % to each, and suggest saving strategies.",
    category: "Awesome Prompts",
    tags: ["finance"],
  },
  {
    id: "meal-prep-scheduler",
    title: "🧠 Meal Prep Scheduler",
    prompt:
      "I want a 7-day meal plan for {diet_type} with prep time <30min per day and total grocery list.",
    category: "Awesome Prompts",
    tags: ["nutrition"],
  },
  {
    id: "travel-packing-list-generator",
    title: "🧠 Travel Packing List Generator",
    prompt:
      "I’m traveling to {destination} for {days} days. Generate a packing list for weather and activities including essentials.",
    category: "Awesome Prompts",
    tags: ["travel"],
  },
  {
    id: "language-practice-buddy",
    title: "🧠 Language Practice Buddy",
    prompt:
      "I’m learning {language}. Generate a 10-question vocabulary quiz on {topic}, then simulate a short dialogue and correct errors.",
    category: "Awesome Prompts",
    tags: ["language_learning"],
  },
  {
    id: "health-check-in-logger",
    title: "🧠 Health Check-in Logger",
    prompt:
      "Create a daily health check-in template asking about sleep quality, mood (1–10), meals, water intake, and exercise.",
    category: "Awesome Prompts",
    tags: ["health"],
  },
  {
    id: "morning-mindset-ritual",
    title: "🧠 Morning Mindset Ritual",
    prompt:
      "Guide me through a 5-minute morning mindset ritual that includes affirmation, visualization, and intention setting for {your_primary_goal}.",
    category: "Awesome Prompts",
    tags: ["mindset"],
  },
  {
    id: "one-sentence-journal",
    title: "🧠 One-Sentence Journal",
    prompt:
      "Ask me one question at day’s end that helps me distill today’s biggest lesson into one powerful sentence.",
    category: "Awesome Prompts",
    tags: ["journaling"],
  },
  {
    id: "proactive-risk-assessor",
    title: "🧠 Proactive Risk Assessor",
    prompt:
      "For my upcoming project on {project_name}, list the top five risks and propose mitigation strategies for each.",
    category: "Awesome Prompts",
    tags: ["risk_management"],
  },
  {
    id: "ideal-week-designer",
    title: "🧠 Ideal Week Designer",
    prompt:
      "Help me design an ideal week based on my priorities: {work}, {family}, {health}, {hobbies}. Suggest blocks and transitions.",
    category: "Awesome Prompts",
    tags: ["scheduling"],
  },
  {
    id: "contextual-focus-trigger",
    title: "🧠 Contextual Focus Trigger",
    prompt:
      "I need to switch gears into deep focus. Give me a 3-step trigger sequence using environment, posture, and affirmation.",
    category: "Awesome Prompts",
    tags: ["focus"],
  },
  {
    id: "task-bundler",
    title: "🧠 Task Bundler",
    prompt:
      "Here’s my list: {tasks}. Organize them into 3 bundles of tasks that can be tackled together in one session.",
    category: "Awesome Prompts",
    tags: ["batching"],
  },
  {
    id: "weekly-theme-planner",
    title: "🧠 Weekly Theme Planner",
    prompt:
      "Help me assign themes to the next four weeks based on my quarterly goals: {goal_list}. Include 3 action items per week.",
    category: "Awesome Prompts",
    tags: ["theming"],
  },
  {
    id: "creative-constraint-generator",
    title: "🧠 Creative Constraint Generator",
    prompt:
      "I need creative ideas for {challenge}. Impose three constraints (e.g., 30min, 3 ingredients, only black & white). Then brainstorm.",
    category: "Awesome Prompts",
    tags: ["creativity"],
  },
  {
    id: "goal-deconstruction",
    title: "🧠 Goal Deconstruction",
    prompt:
      "My objective is {big_goal}. Deconstruct it into quarterly milestones, monthly targets, weekly tasks, and daily habits.",
    category: "Awesome Prompts",
    tags: ["goal_setting"],
  },
  {
    id: "brain-dump-organizer",
    title: "🧠 Brain Dump Organizer",
    prompt:
      "Here’s my raw brain dump: {text}. Extract distinct items, categorize (urgent, important, future), and prioritize.",
    category: "Awesome Prompts",
    tags: ["brain_dump"],
  },
  {
    id: "meeting-notes-summarizer",
    title: "🧠 Meeting Notes Summarizer",
    prompt:
      "Summarize these notes: {meeting_text}. Provide headings: Decisions, Next Actions, Owners, Deadlines.",
    category: "Awesome Prompts",
    tags: ["meetings"],
  },
  {
    id: "energy-audit-questionnaire",
    title: "🧠 Energy Audit Questionnaire",
    prompt:
      "Ask me five probing questions about how I feel during different tasks, then map high-energy vs low-energy slots.",
    category: "Awesome Prompts",
    tags: ["energy"],
  },
  {
    id: "decision-matrix-builder",
    title: "🧠 Decision Matrix Builder",
    prompt:
      "I’m choosing between: {option1}, {option2}, {option3}. Define criteria, weights, score each, and recommend.",
    category: "Awesome Prompts",
    tags: ["decision_making"],
  },
  {
    id: "personalized-pomodoro-timer",
    title: "🧠 Personalized Pomodoro Timer",
    prompt:
      "I focus best for {minutes} then need a break. Recommend a Pomodoro cycle and suggest break activities.",
    category: "Awesome Prompts",
    tags: ["pomodoro"],
  },
  {
    id: "workflow-automation-advisor",
    title: "🧠 Workflow Automation Advisor",
    prompt:
      "List my repetitive tasks: {task_list}. Recommend automations (Zapier, macros, scripts) and basic steps to implement.",
    category: "Awesome Prompts",
    tags: ["automation"],
  },
  {
    id: "productivity-myth-buster",
    title: "🧠 Productivity Myth Buster",
    prompt:
      "Pick a productivity myth (e.g., multitasking boosts output). Explain why it’s false and propose the correct approach.",
    category: "Awesome Prompts",
    tags: ["myths"],
  },
  {
    id: "custom-accountability-report",
    title: "🧠 Custom Accountability Report",
    prompt:
      "Here’s my progress this week: {metrics}. Create a report highlighting successes, gaps, and next steps.",
    category: "Awesome Prompts",
    tags: ["accountability"],
  },
  {
    id: "creativity-warm-up-exercises",
    title: "🧠 Creativity Warm-Up Exercises",
    prompt:
      "Offer me five 3-minute warm-up prompts (e.g., random word association) to boost creativity before tackling {task}.",
    category: "Awesome Prompts",
    tags: ["creativity"],
  },
  {
    id: "proactive-follow-up-helper",
    title: "🧠 Proactive Follow-Up Helper",
    prompt:
      "I met with {contact} about {topic}. Draft a friendly follow-up email summarizing key points and next steps.",
    category: "Awesome Prompts",
    tags: ["email"],
  },
  {
    id: "distraction-replacement-plan",
    title: "🧠 Distraction Replacement Plan",
    prompt:
      "I get distracted by {distraction}. Suggest three replacement activities that satisfy the same urge without derailing my focus.",
    category: "Awesome Prompts",
    tags: ["distraction"],
  },
  {
    id: "rapid-research-guide",
    title: "🧠 Rapid Research Guide",
    prompt:
      "I need quick research on {topic}. Provide a 4-step research plan with suggested sources, methods, and time allocations.",
    category: "Awesome Prompts",
    tags: ["research"],
  },
  {
    id: "digital-clutter-detox",
    title: "🧠 Digital Clutter Detox",
    prompt:
      "Plan a two-day digital detox: tasks to archive/delete files, close unnecessary tabs, organize bookmarks, and uninstall apps.",
    category: "Awesome Prompts",
    tags: ["digital"],
  },
  {
    id: "meeting-prep-snapshot",
    title: "🧠 Meeting Prep Snapshot",
    prompt:
      "Meeting on {topic} with {names}. Generate a one-paragraph brief: context, objectives, questions to ask.",
    category: "Awesome Prompts",
    tags: ["meetings"],
  },
  {
    id: "priority-funnel-designer",
    title: "🧠 Priority Funnel Designer",
    prompt:
      "I receive requests daily. Design a funnel with criteria and steps for triage: respond, schedule, delegate, or defer.",
    category: "Awesome Prompts",
    tags: ["prioritization"],
  },
  {
    id: "micro-learning-snack",
    title: "🧠 Micro-Learning Snack",
    prompt:
      "I have 5 minutes. Teach me the core concept of {topic} with a quick definition, one example, and one takeaway.",
    category: "Awesome Prompts",
    tags: ["learning"],
  },
  {
    id: "habit-stacking-blueprint",
    title: "🧠 Habit Stacking Blueprint",
    prompt:
      "I want to add {new_habit} after {existing_habit}. Propose a habit-stacking plan including cue, routine, reward.",
    category: "Awesome Prompts",
    tags: ["habits"],
  },
  {
    id: "quick-swot-analyst",
    title: "🧠 Quick SWOT Analyst",
    prompt:
      "Perform a SWOT analysis on {project_or_idea}. List strengths, weaknesses, opportunities, threats concisely.",
    category: "Awesome Prompts",
    tags: ["SWOT"],
  },
  {
    id: "context-switch-minimizer",
    title: "🧠 Context Switch Minimizer",
    prompt:
      "Here are today’s tasks: {list}. Sequence them to minimize tool switches and maximize flow.",
    category: "Awesome Prompts",
    tags: ["context_switching"],
  },
  {
    id: "empowering-self-talk-script",
    title: "🧠 Empowering Self-Talk Script",
    prompt:
      "I’m nervous about {event}. Write a 3-sentence self-talk script using my strengths: {strengths_list}.",
    category: "Awesome Prompts",
    tags: ["self-talk"],
  },
  {
    id: "reverse-engineering-success",
    title: "🧠 Reverse Engineering Success",
    prompt:
      "I succeeded at {past_win}. Break down the key decisions, habits, and resources that led to that success.",
    category: "Awesome Prompts",
    tags: ["analysis"],
  },
  {
    id: "3-point-daily-check",
    title: "🧠 3-Point Daily Check",
    prompt:
      "Ask me three things for today: my one focus, an energy-boosting activity, and a self-care action.",
    category: "Awesome Prompts",
    tags: ["daily_routine"],
  },
  {
    id: "workspace-setup-guide",
    title: "🧠 Workspace Setup Guide",
    prompt:
      "Describe how to set up a home office (or desktop workspace) optimized for health, focus, and efficiency.",
    category: "Awesome Prompts",
    tags: ["workspace"],
  },
  {
    id: "contextual-email-sorting",
    title: "🧠 Contextual Email Sorting",
    prompt:
      "I get emails about {projects}. Suggest an email filtering/labeling scheme in Gmail (or Outlook) and sample rules.",
    category: "Awesome Prompts",
    tags: ["email"],
  },
  {
    id: "rapid-brainstorm-synopsis",
    title: "🧠 Rapid Brainstorm Synopsis",
    prompt:
      "I just did a brainstorm: {raw_ideas}. Summarize the top themes and propose next concrete steps.",
    category: "Awesome Prompts",
    tags: ["brainstorm"],
  },
  {
    id: "proactive-calendar-guard",
    title: "🧠 Proactive Calendar Guard",
    prompt:
      "Based on my meeting load this week: {calendar_summary}, suggest where to insert 90-minute focus blocks and 15-minute buffers.",
    category: "Awesome Prompts",
    tags: ["calendar"],
  },
  {
    id: "momentum-builder-micro-tasks",
    title: "🧠 Momentum Builder Micro-Tasks",
    prompt:
      "My project is {big_task}. Suggest three tiny kickoff actions I can complete in 10 minutes each.",
    category: "Awesome Prompts",
    tags: ["momentum"],
  },
  {
    id: "reflective-prompt-vault",
    title: "🧠 Reflective Prompt Vault",
    prompt:
      "My growth focus is {area}. Provide five reflective questions I can journal on each Sunday to track progress.",
    category: "Awesome Prompts",
    tags: ["reflection"],
  },
  {
    id: "life-wheel-assessment",
    title: "🧠 Life Wheel Assessment",
    prompt:
      "Rate my satisfaction 1–10 in Health, Career, Relationships, Finances, Fun, Growth. Then provide one action per domain to boost score.",
    category: "Awesome Prompts",
    tags: ["assessment"],
  },
  {
    id: "future-self-letter",
    title: "🧠 Future Self Letter",
    prompt:
      "Compose a letter from my 5-year-hence self who has achieved {goal}. Include insights on challenges, habits, and mindset needed.",
    category: "Awesome Prompts",
    tags: ["writing"],
  },
  {
    id: "mindful-pause-prompt",
    title: "🧠 Mindful Pause Prompt",
    prompt:
      "At any time, invoke a 2-minute mindful pause: ask me to notice breath, posture, and current emotion, then suggest one action.",
    category: "Awesome Prompts",
    tags: ["mindfulness"],
  },
  {
    id: "long-term-vision-mapping",
    title: "🧠 Long-Term Vision Mapping",
    prompt:
      "I envision myself in 5 years as {vision}. Break it into three pillars (career, personal, health), milestones, and daily habits.",
    category: "Awesome Prompts",
    tags: ["vision"],
  },
  {
    id: "adaptive-goal-refiner",
    title: "🧠 Adaptive Goal Refiner",
    prompt:
      "My goal is {goal}. I’m halfway through and these metrics: {progress}. Recommend refinements to stay on track.",
    category: "Awesome Prompts",
    tags: ["goals"],
  },
  {
    id: "gratitude-flash",
    title: "🧠 Gratitude Flash",
    prompt:
      "Prompt me to list three surprising things I’m grateful for right now and explain why each matters.",
    category: "Awesome Prompts",
    tags: ["gratitude"],
  },
  {
    id: "habit-recovery-guide",
    title: "🧠 Habit Recovery Guide",
    prompt:
      "I missed my habit of {habit} for {missed_days}. Provide a recovery plan to restart momentum without guilt.",
    category: "Awesome Prompts",
    tags: ["habits"],
  },
  {
    id: "creative-problem-solver",
    title: "🧠 Creative Problem-Solver",
    prompt:
      "My problem is {problem_statement}. Use lateral thinking tools (Six Thinking Hats, random word) to propose three novel solutions.",
    category: "Awesome Prompts",
    tags: ["problem_solving"],
  },
  {
    id: "rapid-decision-drill",
    title: "🧠 Rapid Decision Drill",
    prompt:
      "Simulate three rapid-decision scenarios based on {criteria}. Provide options and ask me to choose in 10 seconds each.",
    category: "Awesome Prompts",
    tags: ["decision_speed"],
  },
  {
    id: "context-aware-email-draft",
    title: "🧠 Context-Aware Email Draft",
    prompt:
      "Write an email to {recipient_name}, who is my {relationship}. Topic: {topic}. Choose tone (formal/friendly) accordingly.",
    category: "Awesome Prompts",
    tags: ["email"],
  },
  {
    id: "weekly-resource-curator",
    title: "🧠 Weekly Resource Curator",
    prompt:
      "My focus this week is {skill}. Suggest five resources (with brief descriptions) to accelerate my learning.",
    category: "Awesome Prompts",
    tags: ["learning"],
  },
  {
    id: "morning-priority-flash",
    title: "🧠 Morning Priority Flash",
    prompt:
      "Remind me every 2 hours this morning of my #1 priority: {priority}. Offer a brief motivational line each time.",
    category: "Awesome Prompts",
    tags: ["priorities"],
  },
  {
    id: "continuous-improvement-cycle",
    title: "🧠 Continuous Improvement Cycle",
    prompt:
      "Help me apply PDCA to {project}: define plan, describe execution steps, propose check metrics, and act adjustments.",
    category: "Awesome Prompts",
    tags: ["PDCA"],
  },
  {
    id: "strategic-buffer-block",
    title: "🧠 Strategic Buffer Block",
    prompt:
      "Given my calendar, find natural gaps and suggest three 30-minute buffer blocks for overflow or ideation.",
    category: "Awesome Prompts",
    tags: ["buffers"],
  },
  {
    id: "end-of-day-shutdown-checklist",
    title: "🧠 End-of-Day Shutdown Checklist",
    prompt:
      "Create an end-of-day shutdown checklist covering tasks, next-day planning, and mental closure steps.",
    category: "Awesome Prompts",
    tags: ["shutdown"],
  },
  {
    id: "resource-allocation-matrix",
    title: "🧠 Resource Allocation Matrix",
    prompt:
      "I have three projects, budget $X, and 10 hours/week. Help me allocate resources evenly based on impact.",
    category: "Awesome Prompts",
    tags: ["resources"],
  },
  {
    id: "personal-kpi-dashboard",
    title: "🧠 Personal KPI Dashboard",
    prompt:
      "I care about {metrics_list}. Recommend KPIs, data sources, and a dashboard structure (tool suggestions).",
    category: "Awesome Prompts",
    tags: ["KPI"],
  },
  {
    id: "urgency-vs-importance-drill",
    title: "🧠 Urgency vs Importance Drill",
    prompt:
      "Present five mini-scenarios. For each, I will label U/I matrix quadrant; then provide feedback on my choices.",
    category: "Awesome Prompts",
    tags: ["training"],
  },
  {
    id: "visual-progress-tracker",
    title: "🧠 Visual Progress Tracker",
    prompt:
      "I want to monitor {habit_or_project}. Recommend a visual tracking format and how to update it daily.",
    category: "Awesome Prompts",
    tags: ["visualization"],
  },
  {
    id: "focused-reading-plan",
    title: "🧠 Focused Reading Plan",
    prompt:
      "I have these 5 titles: {list}. Create a 6-week reading plan with time estimates and reflection prompts.",
    category: "Awesome Prompts",
    tags: ["reading"],
  },
  {
    id: "strategic-pause-prompter",
    title: "🧠 Strategic Pause Prompter",
    prompt:
      "Every 2 hours, prompt me with a one-question reflection (e.g., “What’s working? What needs adjustment?”).",
    category: "Awesome Prompts",
    tags: ["pauses"],
  },
  {
    id: "decision-fatigue-reducer",
    title: "🧠 Decision Fatigue Reducer",
    prompt:
      "I waste time deciding {routine_choice}. Propose a simple default choice and a 3-step plan to automate that decision.",
    category: "Awesome Prompts",
    tags: ["decision_fatigue"],
  },
  {
    id: "collaborative-brainstorm-summarizer",
    title: "🧠 Collaborative Brainstorm Summarizer",
    prompt:
      "Here’s our chat transcript: {chat_text}. Summarize top five actionable brainstorm outcomes with next steps.",
    category: "Awesome Prompts",
    tags: ["collaboration"],
  },
  {
    id: "smart-habit-mapper",
    title: "🧠 SMART Habit Mapper",
    prompt:
      "I want to build the habit of {habit}. Turn it into a SMART habit with metric, trigger, and timeframe.",
    category: "Awesome Prompts",
    tags: ["habits"],
  },
  {
    id: "empathy-driven-feedback",
    title: "🧠 Empathy-Driven Feedback",
    prompt:
      "I need to give feedback on {issue} to {person}. Draft a message that balances support, clarity, and suggestions.",
    category: "Awesome Prompts",
    tags: ["feedback"],
  },
  {
    id: "reflect-reset-mid-week",
    title: "🧠 Reflect & Reset Mid-Week",
    prompt:
      "It’s mid-week. Ask me three questions to reflect on progress and adjust priorities for the remaining days.",
    category: "Awesome Prompts",
    tags: ["midweek"],
  },
  {
    id: "strategic-learning-sprint",
    title: "🧠 Strategic Learning Sprint",
    prompt:
      "I have 3 days to learn basics of {skill}. Design a daily sprint plan with study, practice, and review sessions.",
    category: "Awesome Prompts",
    tags: ["learning_sprint"],
  },
  {
    id: "daily-stop-do-continue-logger",
    title: "🧠 Daily “Stop-Do-Continue” Logger",
    prompt:
      "Ask me to list one Stop, one Do, one Continue for today. Then summarize patterns over time if asked.",
    category: "Awesome Prompts",
    tags: ["feedback_loop"],
  },
  {
    id: "quarterly-review-facilitator",
    title: "🧠 Quarterly Review Facilitator",
    prompt:
      "Quarter-end review: ask me to evaluate each KR, reflect lessons, celebrate wins, and set next quarter OKRs.",
    category: "Awesome Prompts",
    tags: ["quarterly"],
  },
  {
    id: "sleep-debt-calculator",
    title: "🧠 Sleep Debt Calculator",
    prompt:
      "I slept {h1}, {h2}, {h3} hours over past three nights. Calculate sleep debt against 8h baseline and suggest recovery plan.",
    category: "Awesome Prompts",
    tags: ["sleep"],
  },
  {
    id: "growth-mindset-primer",
    title: "🧠 Growth Mindset Primer",
    prompt:
      "Explain growth vs fixed mindset, give 3 real-world examples, and craft 5 daily affirmations to internalize growth beliefs.",
    category: "Awesome Prompts",
    tags: ["mindset"],
  },
  {
    id: "digital-wellbeing-check",
    title: "🧠 Digital Wellbeing Check",
    prompt:
      "Assess my screen time habits: {screen_time_data}. Recommend boundaries, app limits, and offline activities.",
    category: "Awesome Prompts",
    tags: ["wellbeing"],
  },
  {
    id: "adaptive-workstyle-profiler",
    title: "🧠 Adaptive Workstyle Profiler",
    prompt:
      "Answer questions about my preferences. Then recommend a daily workstyle plan aligned to my natural rhythm.",
    category: "Awesome Prompts",
    tags: ["workstyle"],
  },
  {
    id: "actionable-insight-extractor",
    title: "🧠 Actionable Insight Extractor",
    prompt:
      "Here’s a long text: {paste_text}. Identify three key insights and recommend a small action for each.",
    category: "Awesome Prompts",
    tags: ["insights"],
  },
] as const;
